import { Project, TaskStatus, TaskPriority, DurationUnit, Currency, UserRole } from '../types';

export const MOCK_PROJECTS: Project[] = [
  {
    id: 'proj-1',
    name: 'Digital Transformation Project Plan (StrategicRefresh 1.0)',
    description: 'A comprehensive plan to fully automate university administration, academics, finance, HR, and student services through an AI-powered, data-driven ecosystem.',
    coreSystem: 'eUniversity ERP + AI, Data Analytics, Blockchain, IoT, Cloud Platforms',
    startDate: new Date('2024-07-01'),
    duration: 8,
    durationUnit: DurationUnit.Weeks,
    team: {
      members: [
        { uid: 'u1', email: 'mohammed@vantageflow.app', displayName: 'Mohammed Mahmud', leadRole: 'primary' },
        { uid: 'u2', email: 'sarah.lead@vantageflow.app', displayName: 'Sarah Connor', leadRole: 'secondary' },
        { uid: 'u3', email: 'alex.dev@vantageflow.app', displayName: 'Alex Rivera' },
      ],
      name: 'Digital Transformation Team',
      size: 15,
      manager: 'Mohammed Mahmud (DLOC)',
    },
    cost: 15000000,
    currency: Currency.NGN,
    phases: [
      {
        id: 'phase-1',
        name: 'Phase 1: Foundation & Architecture',
        weekRange: 'Week 1',
        tasks: [
          {
            id: 't1-1',
            name: 'Establish Project Control Group (PCG)',
            status: TaskStatus.Hundred,
            priority: TaskPriority.Critical,
            startDate: new Date('2024-07-01'),
            endDate: new Date('2024-07-02'),
            assignees: [{ uid: 'u1', email: 'mohammed@vantageflow.app', displayName: 'Mohammed Mahmud' }],
            deliverables: ['PCG charter signed', 'Bi-weekly cadence scheduled'],
          },
          {
            id: 't1-2',
            name: 'Conduct rapid Business Process Review (BPR)',
            status: TaskStatus.Hundred,
            priority: TaskPriority.Important,
            startDate: new Date('2024-07-02'),
            endDate: new Date('2024-07-04'),
            assignees: [{ uid: 'u2', email: 'sarah.lead@vantageflow.app', displayName: 'Sarah Connor' }],
          },
          {
            id: 't1-3',
            name: 'Deploy hybrid cloud & cybersecurity monitoring',
            status: TaskStatus.Hundred,
            priority: TaskPriority.Critical,
            startDate: new Date('2024-07-03'),
            endDate: new Date('2024-07-07'),
            deliverables: ['Cloud IAM policies verified', 'SOC alert webhooks configured'],
          },
        ],
      },
      {
        id: 'phase-2',
        name: 'Phase 2: Core ERP & AI Integration',
        weekRange: 'Week 2-3',
        tasks: [
          {
            id: 't2-1',
            name: 'Deploy Core Modules (Admissions, Registration)',
            status: TaskStatus.Fifty,
            priority: TaskPriority.Critical,
            startDate: new Date('2024-07-08'),
            endDate: new Date('2024-07-15'),
            assignees: [{ uid: 'u3', email: 'alex.dev@vantageflow.app', displayName: 'Alex Rivera' }],
            subTasks: [
              {
                id: 't2-1-1',
                name: 'Configure Admissions Module',
                status: TaskStatus.Hundred,
                priority: TaskPriority.Important,
                startDate: new Date('2024-07-08'),
                endDate: new Date('2024-07-10'),
              },
              {
                id: 't2-1-2',
                name: 'Configure Student Registration Engine',
                status: TaskStatus.Fifty,
                priority: TaskPriority.Critical,
                startDate: new Date('2024-07-11'),
                endDate: new Date('2024-07-13'),
              },
            ],
          },
          {
            id: 't2-2',
            name: 'Launch AI analytics dashboards',
            status: TaskStatus.Fifty,
            priority: TaskPriority.Enhancement,
            startDate: new Date('2024-07-12'),
            endDate: new Date('2024-07-21'),
            assignees: [{ uid: 'u2', email: 'sarah.lead@vantageflow.app', displayName: 'Sarah Connor' }],
          },
          {
            id: 't2-3',
            name: 'Configure SMS/Email + AI chatbots',
            status: TaskStatus.AtRisk,
            priority: TaskPriority.Critical,
            startDate: new Date('2024-07-18'),
            endDate: new Date('2024-07-21'),
            deliverables: ['AI chatbot responding to FAQs', 'SMS gateway latency < 2s'],
          },
        ],
      },
      {
        id: 'phase-3',
        name: 'Phase 3: Extended Digital & Governance',
        weekRange: 'Week 4-6',
        tasks: [
          {
            id: 't3-1',
            name: 'Deploy Google LMS with AI tutors',
            status: TaskStatus.TwentyFive,
            priority: TaskPriority.Important,
            startDate: new Date('2024-07-22'),
            endDate: new Date('2024-08-01'),
          },
          {
            id: 't3-2',
            name: 'Roll out IoT-enabled smart ID & biometric access',
            status: TaskStatus.Zero,
            priority: TaskPriority.Important,
            startDate: new Date('2024-08-12'),
            endDate: new Date('2024-08-18'),
          },
        ],
      },
    ],
  },
  {
    id: 'proj-2',
    name: 'Hospital Information Management System (HIMS)',
    description: 'Patient records, electronic prescriptions, triage prioritization, and lab integrations.',
    coreSystem: 'FastHealthcare FHIR + Cloud Firestore',
    startDate: new Date('2024-09-01'),
    duration: 12,
    durationUnit: DurationUnit.Weeks,
    team: {
      members: [
        { uid: 'u1', email: 'mohammed@vantageflow.app', displayName: 'Mohammed Mahmud', leadRole: 'primary' },
      ],
      name: 'Clinical Operations Team',
      size: 8,
    },
    cost: 45000,
    currency: Currency.USD,
    phases: [
      {
        id: 'p2-1',
        name: 'Phase 1: HIPAA & Cloud Security Setup',
        weekRange: 'Week 1-2',
        tasks: [
          {
            id: 'h-1',
            name: 'Audit FHIR API endpoints and token lifecycle',
            status: TaskStatus.Hundred,
            priority: TaskPriority.Critical,
            startDate: new Date('2024-09-01'),
            endDate: new Date('2024-09-07'),
          },
          {
            id: 'h-2',
            name: 'EHR Encryption at rest & TLS in transit',
            status: TaskStatus.SeventyFive,
            priority: TaskPriority.Critical,
            startDate: new Date('2024-09-08'),
            endDate: new Date('2024-09-14'),
          },
        ],
      },
    ],
  },
];
